version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2025.11
    parallelism: 2
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          name: Parallel Tests
          command: |
            find 'src/' -name "test_*" | circleci tests run --command "xargs -I{} bash {}" --split-by=name
workflows:
  test-workflow:
    jobs:
      - test
