version: 2.1

executors:
  exe-docker:
    docker:
      - image: cimg/node:18.11.0
  exe-machine:
    machine:
      image: ubuntu-2404:2025.09.1
  exe-windows:
    machine:
      image: 'windows-server-2025-gui:current'
      resource_class: windows.medium
      shell: 'powershell.exe -ExecutionPolicy Bypass'
  exe-macos:
    macos:
      xcode: 26.2.0

jobs:
  build:
    parameters:
      exe-name:
        type: string
        default: "docker"
    executor: exe-<< parameters.exe-name >>
    steps:
      - run: echo "<< parameters.exe-name >> executor"

workflows:
  build-docker-workflow:
    jobs:
      - build:
          matrix:
            parameters:
              exe-name: [ "docker", "machine", "windows", "macos" ]
